services:
  app_level_1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: app_level_1
    ports:
      - "5001:5000"
    environment:
      PORT: "5000"

  app_level_2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: app_level_2
    ports:
      - "5002:5000"
    environment:
      PORT: "5000"

  app_level_3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: app_level_3
    ports:
      - "5003:5000"
    environment:
      PORT: "5000"
